### PR TITLE
Add Better Homebrew Browser

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/hackmyvita/hackmyvita.github.io/pull/1
So that it works, you have to accept the pull request from there, otherwise, it won't work.
Also If there's something wrong just tell me and I can fix it.

### CODE REVIEW

**Comment by hedhehd** [comment]
Oh, and the vpk's I can send it.
[Vitadeploy_v.2.0.zip](https://github.com/SKGleba/VitaDeploy/files/8457494/Vitadeploy_v.2.0.zip)

**Comment by SKGleba** [comment]
will add in the next update

**Comment by hedhehd** [comment]
> will add in the next update

Okay 👍

**Comment by SKGleba** [comment]
wontadd, added vitadb downloader, you can download bhbb via it

**Pull request closed without merging**
